# Generated by Django 6.1 on 2026-05-18 18:30

import django.core.validators
import konditerApp.models
import konditerApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konditerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, upload_to=konditerApp.models.product_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'webp']), konditerApp.validators.validate_product_image_extension]),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
