# Generated by Django 6.1 on 2026-05-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konditerApp', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
